version: '3.8'

services:
  tcp-server:
    image: tcp-server:1.0.0
    container_name: tcp-server
    ports:
      - "8080:8080"
      - "8888:8888"
    volumes:
      - ./file:/workspace/files
      - ./server-logs:/logs
    environment:
      - "JAVA_TOOL_OPTIONS=-Xmx512m -Xms256m"
    networks:
      - tcp-network

  tcp-client:
    image: tcp-client:1.0.0
    container_name: tcp-client
    ports:
      - "8081:8081"
    volumes:
      - ./downloads:/downloads
      - ./client-logs:/logs
    environment:
      - "TCP_CLIENT_SERVER_HOST=tcp-server"
      - "TCP_CLIENT_SERVER_PORT=8888"
      - "TCP_CLIENT_DOWNLOAD_DIRECTORY=/downloads"
      - "JAVA_TOOL_OPTIONS=-Xmx256m -Xms128m"
    depends_on:
      - tcp-server
    networks:
      - tcp-network

networks:
  tcp-network:
    driver: bridge