server:
  port: 8080

tcp:
  server:
    port: 8888
    file:
      directory: files

logging:
  level:
    com.example.tcpserver: DEBUG
    io.netty: INFO
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
